### ISSUE TITLE
sending "***" (consecutive stars) as a message gives error

### ISSUE THREAD

**Issue by wilhelmgoering** [mtomwing/pickups#8]
Hi.

I'm using pickups and it works OK.

I've noticed, however, that if you try to send a message with just stars (as in "***"), there is an error and the message is not sent.

Here is the output of the server corresponding to this line:

INFO:pickups.server:Received: 'PRIVMSG #AAAAAAAAA[id] :***'
WARNING:hangups.conversation:Failed to send message: Unexpected status: ERROR_INVALID_REQUEST
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<send_message() done, defined at /usr/lib/python3.4/site-packages/hangups/conversation.py:96> exception=NetworkError('Unexpected status: ERROR_INVALID_REQUEST',)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/usr/lib/python3.4/site-packages/hangups/conversation.py", line 129, in send_message
    image_id=image_id, otr_status=otr_status
  File "/usr/lib/python3.4/site-packages/hangups/client.py", line 436, in sendchatmessage
    .format(res_status))
hangups.exceptions.NetworkError: Unexpected status: ERROR_INVALID_REQUEST

Any ideas? I would inspect the code myself but I'm not familiar with python.

Thank you for your work.

**Comment by tdryer** [comment]
This is a bug in the underlying hangups library. I opened an issue here: https://github.com/tdryer/hangups/issues/149
